### ISSUE TITLE
L2Vault spender allowance reduced when not enough liquidity 

### ISSUE THREAD

**Issue by naddison36** [AffineLabs/contracts#319]
If I understand the L2Vault logic correctly, a `redeem` or `withdraw` when there are not enough assets in the L2 vault will not proceed with the `redeem` or `withdraw`. No assets are transferred to the caller and no shares are burnt. An emergency withdrawal request is queued to transfer more assets to the L2 and the caller can try again later.

But if a spender calls `redeem` or `withdraw` when there are not enough assets in the L2Vault, their allowance is reduced with `_spendAllowance(owner, caller, shares)`. If the number of shares being withdrawn is more than half the allowance, the next withdraw or redeem when the emergency withdrawal request has transferred assets to L2Vault will fail.

**Comment by larryob** [comment]
@naddison36 Yes, the next `redeem` should fail. Users complete redemption by calling [`deque`](https://github.com/AffineLabs/contracts/blob/15a7c41bab1d5cdd15a8d76802e39803f323cd6a/src/vaults/cross-chain-vault/EmergencyWithdrawalQueue.sol#L87) or [`dequeBatch`](https://github.com/AffineLabs/contracts/blob/15a7c41bab1d5cdd15a8d76802e39803f323cd6a/src/vaults/cross-chain-vault/EmergencyWithdrawalQueue.sol#L110) on the `EmergencyWithdrawalQueue`. The deque functions don't update allowances.
